# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hCk3CruWA5je5iCMbt8liXc-OVsBZUUZ
"""

import matplotlib.pyplot as plt
import numpy as np

x=np.array([0,6])
y=np.array([0,250])

plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([1,2,6,8])
y=np.array([3,8,1,10])

plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([1,2,3,4,5,6,7,8])
y=np.array([3,8,1,10,2,6,1,8])

plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([1,2,6,8])
y=np.array([3,8,1,10])

plt.plot(y, marker='+')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([1,2,6,8])
y=np.array([3,8,1,10])

plt.plot(y, '+:r')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([1,2,6,8])
y=np.array([3,8,1,10])

plt.plot(y, marker='+',ms=25,mec='r')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([2,2,6,6,5.5,2.5,5.5,2.5,3,5,3,5])
y=np.array([4,8,4,8,7.5,4.5,4.5,7.5,5,5,7,7])
mycolor=['red','green','aqua','lime','purple','red','green','aqua','lime','purple','red','green']
size=[100,150,100,150,100,150,100,150,100,150,100,150]
plt.scatter(x,y,color=mycolor,s=size)

plt.show()